// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: authorizationService.proto

package ru.vtb.s7.client.mkb.grpc;

public final class AuthorizationService {
  private AuthorizationService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032authorizationService.proto\032\032authorizat" +
      "ionRequest.proto\032\030authorizationReply.pro" +
      "to2I\n\rAuthorization\0228\n\010SayHello\022\025.Author" +
      "izationRequest\032\023.AuthorizationReply\"\000B\035\n" +
      "\031ru.vtb.s7.client.mkb.grpcP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          ru.vtb.s7.client.mkb.grpc.AuthorizationRequestOuterClass.getDescriptor(),
          ru.vtb.s7.client.mkb.grpc.AuthorizationReplyOuterClass.getDescriptor(),
        });
    ru.vtb.s7.client.mkb.grpc.AuthorizationRequestOuterClass.getDescriptor();
    ru.vtb.s7.client.mkb.grpc.AuthorizationReplyOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
