// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: authorizationRequest.proto

package ru.vtb.s7.client.mkb.grpc;

public interface AuthorizationRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AuthorizationRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
