// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client.proto

package ru.vtb.s7.client.mkb.grpc;

/**
 * <pre>
 * добавить клиенту пропс
 * </pre>
 *
 * Protobuf type {@code ClientAddInnRequest}
 */
public  final class ClientAddInnRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ClientAddInnRequest)
    ClientAddInnRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ClientAddInnRequest.newBuilder() to construct.
  private ClientAddInnRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ClientAddInnRequest() {
    idClient_ = "";
    inn_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ClientAddInnRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ClientAddInnRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            idClient_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            inn_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ru.vtb.s7.client.mkb.grpc.ClientOuterClass.internal_static_ClientAddInnRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ru.vtb.s7.client.mkb.grpc.ClientOuterClass.internal_static_ClientAddInnRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ru.vtb.s7.client.mkb.grpc.ClientAddInnRequest.class, ru.vtb.s7.client.mkb.grpc.ClientAddInnRequest.Builder.class);
  }

  public static final int IDCLIENT_FIELD_NUMBER = 1;
  private volatile java.lang.Object idClient_;
  /**
   * <code>string idClient = 1;</code>
   * @return The idClient.
   */
  public java.lang.String getIdClient() {
    java.lang.Object ref = idClient_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      idClient_ = s;
      return s;
    }
  }
  /**
   * <code>string idClient = 1;</code>
   * @return The bytes for idClient.
   */
  public com.google.protobuf.ByteString
      getIdClientBytes() {
    java.lang.Object ref = idClient_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      idClient_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int INN_FIELD_NUMBER = 2;
  private volatile java.lang.Object inn_;
  /**
   * <code>string inn = 2;</code>
   * @return The inn.
   */
  public java.lang.String getInn() {
    java.lang.Object ref = inn_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      inn_ = s;
      return s;
    }
  }
  /**
   * <code>string inn = 2;</code>
   * @return The bytes for inn.
   */
  public com.google.protobuf.ByteString
      getInnBytes() {
    java.lang.Object ref = inn_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      inn_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getIdClientBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, idClient_);
    }
    if (!getInnBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, inn_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getIdClientBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, idClient_);
    }
    if (!getInnBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, inn_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ru.vtb.s7.client.mkb.grpc.ClientAddInnRequest)) {
      return super.equals(obj);
    }
    ru.vtb.s7.client.mkb.grpc.ClientAddInnRequest other = (ru.vtb.s7.client.mkb.grpc.ClientAddInnRequest) obj;

    if (!getIdClient()
        .equals(other.getIdClient())) return false;
    if (!getInn()
        .equals(other.getInn())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + IDCLIENT_FIELD_NUMBER;
    hash = (53 * hash) + getIdClient().hashCode();
    hash = (37 * hash) + INN_FIELD_NUMBER;
    hash = (53 * hash) + getInn().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ru.vtb.s7.client.mkb.grpc.ClientAddInnRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ru.vtb.s7.client.mkb.grpc.ClientAddInnRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ru.vtb.s7.client.mkb.grpc.ClientAddInnRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ru.vtb.s7.client.mkb.grpc.ClientAddInnRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ru.vtb.s7.client.mkb.grpc.ClientAddInnRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ru.vtb.s7.client.mkb.grpc.ClientAddInnRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ru.vtb.s7.client.mkb.grpc.ClientAddInnRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ru.vtb.s7.client.mkb.grpc.ClientAddInnRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ru.vtb.s7.client.mkb.grpc.ClientAddInnRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ru.vtb.s7.client.mkb.grpc.ClientAddInnRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ru.vtb.s7.client.mkb.grpc.ClientAddInnRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ru.vtb.s7.client.mkb.grpc.ClientAddInnRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ru.vtb.s7.client.mkb.grpc.ClientAddInnRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * добавить клиенту пропс
   * </pre>
   *
   * Protobuf type {@code ClientAddInnRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ClientAddInnRequest)
      ru.vtb.s7.client.mkb.grpc.ClientAddInnRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ru.vtb.s7.client.mkb.grpc.ClientOuterClass.internal_static_ClientAddInnRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ru.vtb.s7.client.mkb.grpc.ClientOuterClass.internal_static_ClientAddInnRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ru.vtb.s7.client.mkb.grpc.ClientAddInnRequest.class, ru.vtb.s7.client.mkb.grpc.ClientAddInnRequest.Builder.class);
    }

    // Construct using ru.vtb.s7.client.mkb.grpc.ClientAddInnRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      idClient_ = "";

      inn_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ru.vtb.s7.client.mkb.grpc.ClientOuterClass.internal_static_ClientAddInnRequest_descriptor;
    }

    @java.lang.Override
    public ru.vtb.s7.client.mkb.grpc.ClientAddInnRequest getDefaultInstanceForType() {
      return ru.vtb.s7.client.mkb.grpc.ClientAddInnRequest.getDefaultInstance();
    }

    @java.lang.Override
    public ru.vtb.s7.client.mkb.grpc.ClientAddInnRequest build() {
      ru.vtb.s7.client.mkb.grpc.ClientAddInnRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ru.vtb.s7.client.mkb.grpc.ClientAddInnRequest buildPartial() {
      ru.vtb.s7.client.mkb.grpc.ClientAddInnRequest result = new ru.vtb.s7.client.mkb.grpc.ClientAddInnRequest(this);
      result.idClient_ = idClient_;
      result.inn_ = inn_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ru.vtb.s7.client.mkb.grpc.ClientAddInnRequest) {
        return mergeFrom((ru.vtb.s7.client.mkb.grpc.ClientAddInnRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ru.vtb.s7.client.mkb.grpc.ClientAddInnRequest other) {
      if (other == ru.vtb.s7.client.mkb.grpc.ClientAddInnRequest.getDefaultInstance()) return this;
      if (!other.getIdClient().isEmpty()) {
        idClient_ = other.idClient_;
        onChanged();
      }
      if (!other.getInn().isEmpty()) {
        inn_ = other.inn_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ru.vtb.s7.client.mkb.grpc.ClientAddInnRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ru.vtb.s7.client.mkb.grpc.ClientAddInnRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object idClient_ = "";
    /**
     * <code>string idClient = 1;</code>
     * @return The idClient.
     */
    public java.lang.String getIdClient() {
      java.lang.Object ref = idClient_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        idClient_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string idClient = 1;</code>
     * @return The bytes for idClient.
     */
    public com.google.protobuf.ByteString
        getIdClientBytes() {
      java.lang.Object ref = idClient_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        idClient_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string idClient = 1;</code>
     * @param value The idClient to set.
     * @return This builder for chaining.
     */
    public Builder setIdClient(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      idClient_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string idClient = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearIdClient() {
      
      idClient_ = getDefaultInstance().getIdClient();
      onChanged();
      return this;
    }
    /**
     * <code>string idClient = 1;</code>
     * @param value The bytes for idClient to set.
     * @return This builder for chaining.
     */
    public Builder setIdClientBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      idClient_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object inn_ = "";
    /**
     * <code>string inn = 2;</code>
     * @return The inn.
     */
    public java.lang.String getInn() {
      java.lang.Object ref = inn_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        inn_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string inn = 2;</code>
     * @return The bytes for inn.
     */
    public com.google.protobuf.ByteString
        getInnBytes() {
      java.lang.Object ref = inn_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        inn_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string inn = 2;</code>
     * @param value The inn to set.
     * @return This builder for chaining.
     */
    public Builder setInn(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      inn_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string inn = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearInn() {
      
      inn_ = getDefaultInstance().getInn();
      onChanged();
      return this;
    }
    /**
     * <code>string inn = 2;</code>
     * @param value The bytes for inn to set.
     * @return This builder for chaining.
     */
    public Builder setInnBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      inn_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ClientAddInnRequest)
  }

  // @@protoc_insertion_point(class_scope:ClientAddInnRequest)
  private static final ru.vtb.s7.client.mkb.grpc.ClientAddInnRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ru.vtb.s7.client.mkb.grpc.ClientAddInnRequest();
  }

  public static ru.vtb.s7.client.mkb.grpc.ClientAddInnRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ClientAddInnRequest>
      PARSER = new com.google.protobuf.AbstractParser<ClientAddInnRequest>() {
    @java.lang.Override
    public ClientAddInnRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ClientAddInnRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ClientAddInnRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ClientAddInnRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ru.vtb.s7.client.mkb.grpc.ClientAddInnRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

