// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client.proto

package ru.vtb.s7.client.mkb.grpc;

public interface ClientNewRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ClientNewRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
