// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client.proto

package ru.vtb.s7.client.mkb.grpc;

public final class ClientOuterClass {
  private ClientOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ClientNewRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ClientNewRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ClientNewReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ClientNewReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ClientAddInnRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ClientAddInnRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ClientAddInnReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ClientAddInnReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014client.proto\" \n\020ClientNewRequest\022\014\n\004na" +
      "me\030\002 \001(\t\"9\n\016ClientNewReply\022\016\n\006status\030\001 \001" +
      "(\t\022\n\n\002id\030\002 \001(\t\022\013\n\003msg\030\003 \001(\t\"4\n\023ClientAdd" +
      "InnRequest\022\020\n\010idClient\030\001 \001(\t\022\013\n\003inn\030\002 \001(" +
      "\t\"0\n\021ClientAddInnReply\022\016\n\006status\030\001 \001(\t\022\013" +
      "\n\003inn\030\002 \001(\t2k\n\006Client\0221\n\tCreateNew\022\021.Cli" +
      "entNewRequest\032\017.ClientNewReply\"\000\022.\n\006AddI" +
      "nn\022\021.ClientNewRequest\032\017.ClientNewReply\"\000" +
      "B\035\n\031ru.vtb.s7.client.mkb.grpcP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ClientNewRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ClientNewRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ClientNewRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_ClientNewReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ClientNewReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ClientNewReply_descriptor,
        new java.lang.String[] { "Status", "Id", "Msg", });
    internal_static_ClientAddInnRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ClientAddInnRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ClientAddInnRequest_descriptor,
        new java.lang.String[] { "IdClient", "Inn", });
    internal_static_ClientAddInnReply_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_ClientAddInnReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ClientAddInnReply_descriptor,
        new java.lang.String[] { "Status", "Inn", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
