// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client.proto

package ru.vtb.s7.client.mkb.grpc;

public interface ClientAddInnReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ClientAddInnReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string status = 1;</code>
   * @return The status.
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 1;</code>
   * @return The bytes for status.
   */
  com.google.protobuf.ByteString
      getStatusBytes();

  /**
   * <code>string inn = 2;</code>
   * @return The inn.
   */
  java.lang.String getInn();
  /**
   * <code>string inn = 2;</code>
   * @return The bytes for inn.
   */
  com.google.protobuf.ByteString
      getInnBytes();
}
