// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client.proto

package ru.vtb.s7.client.mkb.grpc;

public interface ClientAddInnRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ClientAddInnRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string idClient = 1;</code>
   * @return The idClient.
   */
  java.lang.String getIdClient();
  /**
   * <code>string idClient = 1;</code>
   * @return The bytes for idClient.
   */
  com.google.protobuf.ByteString
      getIdClientBytes();

  /**
   * <code>string inn = 2;</code>
   * @return The inn.
   */
  java.lang.String getInn();
  /**
   * <code>string inn = 2;</code>
   * @return The bytes for inn.
   */
  com.google.protobuf.ByteString
      getInnBytes();
}
