/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.vtb.blockchain.client.mkb;

public class Application {
    public static void main(String[] args) {
        ExchangeMsg exchangeMsg = new ExchangeMsg();
        DaemonEnterText keyDaemon = new DaemonEnterText(new AdapterExchangeMsgToDaemonEnterText(exchangeMsg));

        keyDaemon.start();

        while (!keyDaemon.isExit) {
            Thread.yield();
        }
    }
}
