/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.vtb.blockchain.client.mkb;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        Application classUnderTest = new Application();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
