// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: connect.proto

package ru.vtb.blockchain.client.mkb.grpc;

public final class ConnectOuterClass {
  private ConnectOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rconnect.proto\022!ru.vtb.blockchain.clien" +
      "t.mkb.grpc\032\017handshake.proto2w\n\007Connect\022l" +
      "\n\010SayHello\022/.ru.vtb.blockchain.client.mk" +
      "b.grpc.HelloRequest\032-.ru.vtb.blockchain." +
      "client.mkb.grpc.HelloReply\"\000B\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          ru.vtb.blockchain.client.mkb.grpc.Handshake.getDescriptor(),
        });
    ru.vtb.blockchain.client.mkb.grpc.Handshake.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
