// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: handshake.proto

package ru.vtb.blockchain.client.mkb.grpc;

public interface HelloReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ru.vtb.blockchain.client.mkb.grpc.HelloReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
